### ISSUE TITLE
Ports when using nginx as forwarding proxy

### ISSUE THREAD

**Issue by saschafoerster** [jboxberger/synology-gitlab-jboxberger#3]
Hi there: I want to use a regular subdomain like https://code.company.com (with port 443). I can use nginx forwarding in Synology and everything works (from port 443 to port 30000 inside the docker container). 
But Gitlab itself still thinks, it sits behind this URL: https://code.company.com:30000. How can I change this?

**Comment by jboxberger** [comment]
Hi Sascha

the port 30000 is a registered Docker Port witch is dedicated assigened to the Image. You can specify the Port on intsall or afterwards in the docker Configuration. THe Webserver running the DSM gets all connections on Port 30000 and forwards them to the Docker Gitlab Container. You can not get rid of the Port because by leaving out the Port it defaults to Port 80 and this is kind of "reserved". We had that Problem in the Past [here](https://github.com/jboxberger/synology-gitlab-jboxberger/issues/1). Docker blocks any mapping on Port 80 or 443 directly. Because of this i blocked this Ports on the Installer. So there is no way to remap the Port to 80, 443. Any other Port is a "custom" Port will work but they lead you to the "ugly" links like https://code.company.com:<cusom port>.

So there is, as far as i understood it right, no way to get rid of the port in your links.

Kind Regards

**Comment by tobidemski** [comment]
Hey guys,
i think it is possible.. You have to define the gitlab env variable "GITLAB_PORT" with 443 and "GITLAB_HTTPS" to true.

Currently my git repo urls are like this:
https://gitlab.DOMAIN.de/PROJECTNAME/PROJECT.Solution.git

Im not sure if i have to re-set this ports after every update on my synology or it was saved.

Greetz

**Comment by saschafoerster** [comment]
I had to search, where I can add this env variables. Stopped the docker container in DSM, changed the entry with editing the container, restarted: and it just works! Now I've got port 443 with nginx-proxy in the frontend, port 3000 for docker and port 443 in the GITLAB_PORT-variable, which creates correct links, but keeps the network-route working! Case solved!

**Comment by jboxberger** [comment]
Yes this will work for you because of the Nginx Proxy, By Default your domain https://gitlab.DOMAIN.de/PROJECTNAME/PROJECT.Solution.git will be redirected to https://gitlab.DOMAIN.de:5001 so the GITLAB_PORT=443 ENVVAR supress the Port ":30000" in the URL and breaks the URL at the same time (not working without proxy) . 

I'am glad this works for you.

Maybe you want to apply your port change to /var/packages/synology-gitlab-jboxberger/etc/config. This configuration will be restored on each update. So your update may potentially break without updating the ../config file.

Kind Regards

**Comment by saschafoerster** [comment]
And it just works with updates! Thanks for your help!
